name: py313
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - aom=3.9.1=he0c23c2_0
  - async_generator=1.10=pyhd8ed1ab_2
  - attrs=25.4.0=pyhcf101f3_1
  - backports.asyncio.runner=1.2.0=pyh5ded981_2
  - backports.zstd=1.3.0=py313h2a31948_0
  - brotli-python=1.2.0=py313h3ebfc14_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py313h5ea7bf4_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fake-useragent=2.2.0=py313hfa70ccb_1
  - ffmpeg=8.0.1=gpl_hb2d76f6_912
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.44.5=h1f5b9c4_0
  - gevent=25.9.1=py313h5fd188c_1
  - glslang=16.2.0=h294ba9c_1
  - graphite2=1.3.14=hac47afa_2
  - greenlet=3.3.1=py313h927ade5_1
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h5a1b470_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=pyhfb79c49_0
  - imageio-ffmpeg=0.6.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jsonpath-ng=1.7.0=pyhe01879c_0
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_17
  - libglib=2.86.3=h0c9aed9_1
  - libgomp=15.2.0=h8ee18e1_17
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.2=hf3f85d1_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libmpdec=4.0.0=hfd05255_1
  - libogg=1.3.5=h2466b09_1
  - libopus=1.6.1=h6a83c73_0
  - libpng=1.6.55=h7351971_0
  - librsvg=2.60.0=hd5e4115_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.341.0=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - loguru=0.7.3=pyh7428d3b_0
  - lxml=6.0.2=py313h1af1686_2
  - mkl=2025.3.0=hac47afa_455
  - moviepy=2.2.1=pyhd8ed1ab_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - numpy=2.4.2=py313hce7ae62_1
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.4=h24db6dd_0
  - openpyxl=3.1.5=py313hc624790_3
  - openssl=3.6.1=hf411b9b_1
  - outcome=1.3.0.post0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py313h26f5e95_0
  - pandas-stubs=3.0.0.260204=pyhd8ed1ab_1
  - pango=1.56.4=h03d888a_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=10.4.0=py313h24ec7aa_1
  - pip=26.0.1=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - pluggy=1.6.0=pyhf9edf01_1
  - ply=3.11=pyhd8ed1ab_3
  - proglog=0.1.10=pyhaa61c55_0
  - pthread-stubs=0.4=h0e40799_1002
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymysql=1.1.2=pyhcf101f3_0
  - pypdf=6.7.0=pyhcf101f3_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-asyncio=1.3.0=pyhcf101f3_0
  - python=3.13.12=h09917c8_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-docx=1.2.0=pyhff2d567_0
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-pptx=1.0.2=pyhcf101f3_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - requests=2.32.5=pyhcf101f3_1
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.4.0=h5112557_0
  - selenium=4.40.0=pyhcf101f3_0
  - selenium-manager=4.40.0=h18a1a76_0
  - setuptools=82.0.0=pyh332efcf_0
  - shaderc=2025.5=h8fa7867_1
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - spirv-tools=2026.1=h49e36cd_0
  - svt-av1=4.0.1=hac47afa_0
  - tbb=2022.3.0=h3155e25_2
  - tenacity=9.1.4=pyhcf101f3_0
  - tk=8.6.13=h6ed50ae_3
  - tomli=2.4.0=pyhcf101f3_0
  - tqdm=4.67.3=pyha7b4d00_0
  - trio=0.32.0=py313h3a11399_1
  - trio-typing=0.10.0=pyhd8ed1ab_1
  - trio-websocket=0.12.2=pyh29332c3_0
  - types-certifi=2021.10.8.3=pyhd8ed1ab_1
  - types-pytz=2025.2.0.20251108=pyhd8ed1ab_0
  - types-urllib3=1.26.25.14=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - win32_setctime=1.2.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wsproto=1.3.2=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xlsxwriter=3.2.9=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zipp=3.23.0=pyhcf101f3_1
  - zope.event=6.1=pyhcf101f3_0
  - zope.interface=8.0.1=py313h5fd188c_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - cryptography==46.0.5
      - pdfminer-six==20251230
      - pdfplumber==0.11.9
      - pypdfium2==5.4.0
prefix: D:\miniconda3\envs\py313
